### ISSUE TITLE
Issue with pickle5 on install with setup.py

### ISSUE THREAD

**Issue by CPQE** [bkitej/derpcache#1]
Here's the error message, trying to install this on windows10 using python3.8: 
Collecting pickle5
  Using cached pickle5-0.0.11.tar.gz (132 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for pickle5, since package 'wheel' is not installed.
Building wheels for collected packages: derpcache
  Building wheel for derpcache (pyproject.toml) ... done
  Created wheel for derpcache: filename=derpcache-0.0.1-py3-none-any.whl size=2991 sha256=5cda33445fadeec259938dd5f57a3c423e01b21443b31df94d1c75340ea4339f
  Stored in directory: C:\Users\cyrus\AppData\Local\Temp\pip-ephem-wheel-cache-lf_fekad\wheels\be\b1\64\23518fa97fe9f7ac2d8a1c779dff93aca992195ac3b626d270
Successfully built derpcache
Installing collected packages: pickle5, derpcache
  Running setup.py install for pickle5 ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pickle5 did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\pickle5
      copying pickle5\pickle.py -> build\lib.win-amd64-3.9\pickle5
      copying pickle5\pickletools.py -> build\lib.win-amd64-3.9\pickle5
      copying pickle5\__init__.py -> build\lib.win-amd64-3.9\pickle5
      creating build\lib.win-amd64-3.9\pickle5\test
      copying pickle5\test\pickletester.py -> build\lib.win-amd64-3.9\pickle5\test
      copying pickle5\test\test_pickle.py -> build\lib.win-amd64-3.9\pickle5\test
      copying pickle5\test\test_picklebuffer.py -> build\lib.win-amd64-3.9\pickle5\test
      copying pickle5\test\__init__.py -> build\lib.win-amd64-3.9\pickle5\test
      running build_ext
      building 'pickle5._pickle' extension
      creating build\temp.win-amd64-3.9
      creating build\temp.win-amd64-3.9\Release
      creating build\temp.win-amd64-3.9\Release\pickle5
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\cyrus\AppData\Local\Programs\Python\Python39\include -IC:\Users\cyrus\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um /Tcpickle5/_pickle.c /Fobuild\temp.win-amd64-3.9\Release\pickle5/_pickle.obj
      _pickle.c
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\cyrus\AppData\Local\Programs\Python\Python39\include -IC:\Users\cyrus\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um /Tcpickle5/picklebufobject.c /Fobuild\temp.win-amd64-3.9\Release\pickle5/picklebufobject.obj
      picklebufobject.c
      pickle5/picklebufobject.c(19): warning C4273: 'PyPickleBuffer_FromObject': inconsistent dll linkage
      C:\Users\cyrus\AppData\Local\Programs\Python\Python39\include\picklebufobject.h(18): note: see previous definition of 'PyPickleBuffer_FromObject'
      pickle5/picklebufobject.c(38): warning C4273: 'PyPickleBuffer_GetBuffer': inconsistent dll linkage
      C:\Users\cyrus\AppData\Local\Programs\Python\Python39\include\picklebufobject.h(22): note: see previous definition of 'PyPickleBuffer_GetBuffer'
      pickle5/picklebufobject.c(57): warning C4273: 'PyPickleBuffer_Release': inconsistent dll linkage
      C:\Users\cyrus\AppData\Local\Programs\Python\Python39\include\picklebufobject.h(24): note: see previous definition of 'PyPickleBuffer_Release'
      pickle5/picklebufobject.c(208): warning C4273: 'PyPickleBuffer_Type': inconsistent dll linkage
      C:\Users\cyrus\AppData\Local\Programs\Python\Python39\include\picklebufobject.h(13): note: see previous definition of 'PyPickleBuffer_Type'
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\cyrus\AppData\Local\Programs\Python\Python39\libs /LIBPATH:C:\Users\cyrus\AppData\Local\Programs\Python\Python39\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64 /EXPORT:PyInit__pickle build\temp.win-amd64-3.9\Release\pickle5/_pickle.obj build\temp.win-amd64-3.9\Release\pickle5/picklebufobject.obj /OUT:build\lib.win-amd64-3.9\pickle5\_pickle.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\pickle5\_pickle.cp39-win_amd64.lib
      python39.lib(python39.dll) : error LNK2005: PyPickleBuffer_GetBuffer already defined in picklebufobject.obj
         Creating library build\temp.win-amd64-3.9\Release\pickle5\_pickle.cp39-win_amd64.lib and object build\temp.win-amd64-3.9\Release\pickle5\_pickle.cp39-win_amd64.exp
      build\lib.win-amd64-3.9\pickle5\_pickle.cp39-win_amd64.pyd : fatal error LNK1169: one or more multiply defined symbols found
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\link.exe' failed with exit code 1169
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pickle5

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by bkitej** [comment]
> inconsistent dll linkage

Seems like a system thing—I'm not a Windows user so I at least can't help you with this.

Always worth trying to run your project out of a docker container.

**Comment by CPQE** [comment]
Hello sir, 
I tried to download on Fedora Linux  33 (using Python 3.9) with similar dismal results. This time the system seemed to be able to download pickle5 but it still failed to build the .whl. 

 ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fvze0he0/pickle5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fvze0he0/pickle5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yiya1mra/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/cyrus/.local/include/python3.9/pickle5
         cwd: /tmp/pip-install-fvze0he0/pickle5/
    Complete output (25 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/pickle5
    copying pickle5/pickletools.py -> build/lib.linux-x86_64-3.9/pickle5
    copying pickle5/pickle.py -> build/lib.linux-x86_64-3.9/pickle5
    copying pickle5/__init__.py -> build/lib.linux-x86_64-3.9/pickle5
    creating build/lib.linux-x86_64-3.9/pickle5/test
    copying pickle5/test/test_picklebuffer.py -> build/lib.linux-x86_64-3.9/pickle5/test
    copying pickle5/test/test_pickle.py -> build/lib.linux-x86_64-3.9/pickle5/test
    copying pickle5/test/pickletester.py -> build/lib.linux-x86_64-3.9/pickle5/test
    copying pickle5/test/__init__.py -> build/lib.linux-x86_64-3.9/pickle5/test
    running build_ext
    building 'pickle5._pickle' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/pickle5
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.9 -c pickle5/_pickle.c -o build/temp.linux-x86_64-3.9/pickle5/_pickle.o -std=c99
    In file included from pickle5/_pickle.c:2:
    pickle5/compat.h:1:10: fatal error: Python.h: No such file or directory
        1 | #include "Python.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fvze0he0/pickle5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fvze0he0/pickle5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yiya1mra/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/cyrus/.local/include/python3.9/pickle5 Check the logs for full command output.

I'll try to look into a docker container like you suggested.

**Comment by bkitej** [comment]
Seems like this a `pickle5` issue, I recommend you bring these issues to them.
